# LBB Announcement

Dear Bapak/Ibu,

Selamat atas keberhasilannya melewati 3 hari pembelajaran di kelas **DSS - Optimizing Logistics Distribution Routes: A Graph Theory Approach**! Dalam rangka meningkatkan kemampuan Bapak dan Ibu dalam mengimplementasikan ilmu yang didapatkan di kelas, kami menyediakan modul Learn by Building (LBB) sebagai sarana Bapak dan Ibu untuk berlatih dalam membangun study case.

Modul LBB ini akan menjadi syarat Bapak/Ibu untuk mendapatkan sertifikat pembelajaran DSS pada kali ini. Pengerjaan LBB ini juga akan meningkatkan skill sebagai seorang Data Scientist agar dapat mengerjakan modul tambahan ini, hasil dari model tambahan ini dapat ditambahkan sebagai portofolio pribadi.

# LBB Rubrics

## Rubrics
Dalam pembuatan report, jangan lupa untuk menyertakan hal-hal berikut:

1. Import Data
2. Data Preprocessing & Feature Engineering: Create weight from Total Cost
3. Pembentukan Graph dan Visualisasi Graf
4. Pencarian Rute Optimal 
5. [Optional] Visualisasi Rute Baru
6. [Optional] Travelling Salesman Problem (TSP)

## Dataset

Kita adalah seorang data saintis di sebuah perusahaan produsen makanan dingin di Makassar. Kita diberikan data `records_mks`, dan `lokasi_makassar` yang berisi informasi pengiriman antar lokasinya.

In [3]:
import pandas as pd

pd.read_csv('records_mks.csv').head(6)

,start,end,lokasi_start,latitude_start,longitude_start,lokasi_end,latitude_end,longitude_end,dist,lge/100km,add_cost,start_time,end_time
0,B,D,Nipah Mall,-5.138213,119.450386,Mall Ratu Indah,-5.152877,119.417858,7.5,15.08,0.0,2023-05-03 15:20:00,2023-05-03 15:45:00
1,A,B,Warehouse,-5.094272,119.491642,Nipah Mall,-5.138213,119.450386,11.0,13.52,15.5,2023-05-03 14:19:00,2023-05-03 14:44:00
2,F,G,Makassar Town Square,-5.139702,119.473848,Phinisi Point,-5.151032,119.404404,12.3,16.03,0.0,2023-05-02 15:10:00,2023-05-02 15:48:00
3,A,F,Warehouse,-5.094272,119.491642,Makassar Town Square,-5.139702,119.473848,9.7,14.45,0.0,2023-05-02 14:13:00,2023-05-02 14:39:00
4,E,C,Mall Panakkukang,-5.156903,119.446034,TSM Makassar,-5.158039,119.394943,9.8,15.27,0.0,2023-05-01 15:02:00,2023-05-01 15:33:00
5,A,E,Warehouse,-5.094272,119.491642,Mall Panakkukang,-5.156903,119.446034,14.2,12.72,15.5,2023-05-01 14:02:00,2023-05-01 14:28:00

**Deskripsi Data:**

Data `records` merupakan kumpulan catatan pengiriman distribusi. Berikut informasi dari setiap kolom:

- `start`: Lokasi berangkat
- `end`: Lokasi tujuan
- `lokasi_start`: Nama lokasi awal
- `latitude_start`: Titik latitude lokasi awal
- `longitude_start`: Titik longitude lokasi awal
- `lokasi_end`: Nama lokasi tujuan
- `latitude_end`: Titik latitude lokasi tujuan
- `longitude_end`: Titik longitude lokasi tujuan
- `dist`: Jarak tempuh (satuan km)
- `lge/100km`: Penggunaan liter bensin / 100 km
- `add_cost`: Tambahan biaya dalam satuan Ribu Rupiah (Biaya Tol)
- `start_time`: Waktu berangkat
- `end_time`: Waktu tiba

### BATASAN MASALAH

Selain informasi dari data ini, kita juga mengetahui beberapa informasi antara lain:

**Aturan**

- A (warehouse) adalah pusat penyimpanan. Setiap jalur distribusi berawal dari titik A

- Kebutuhan produk perminggu setiap lokasi adalah 1 ton.

- Truk dapat mengangkut produk dengan berat maksimal 2,2 ton.

- Waktu drop di setiap lokasi adalah -+ 30 menit

**Biaya:**

- Bahan bakar yang digunakan truk adalah Dexlite (Rp14,950/liter)

- Biaya pengeluaran mesin pendingin truk adalah Rp9,000/jam

> âš  Disclaimer: Bisnis problem dan data bersifat *dummy* yang terinspirasi dari hasil penelitian Liang, Wu dan Sun <sup>[[2](https://doi.org/10.2991/asei-15.2015.145)]</sup> dimana mencari rute optimal pada kasus cold chain logistics menggunakan Particle Swarm Optimization (PSO). Inspirasi lain juga berasal dari artikel Samir Saci <sup>[[3](https://towardsdatascience.com/transportation-network-analysis-with-graph-theory-55eceb7e4de4)]</sup> yang melakukan analisis jaringan distribusi menggunakan Teori Graf.

# Submission

Bapak/Ibu selamat-lambatnya bisa menggumpulkkan hasil LBB yang sudah dikerjakan pada hari Kamis, 29 Juni 2023. Dengan cara melampirkan di google classroom hasil file dalam bentuk .zip yang berisi dataset yang digunakan dan .ipynb yang berisi code dan narasi dalam pengerjaan workflow pencarian rute optimal menggunakan graf.